#include "motors.h"

/* Handles generated by CubeMX in main.c */
extern TIM_HandleTypeDef htim4;   /* motor A drive, CH3 + CH4 */
extern TIM_HandleTypeDef htim9;   /* motor B drive, CH1 + CH2 */
extern TIM_HandleTypeDef htim12;  /* steering servo, CH2 */

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

static uint32_t speed_to_ccr(int16_t speed)
{
    int32_t mag = (speed < 0) ? -(int32_t)speed : (int32_t)speed;

    if (mag > MOTOR_SPEED_MAX)
    {
        mag = MOTOR_SPEED_MAX;
    }

    /* Worst case 1000 * 4199 = 4199000, comfortably inside int32. */
    return (uint32_t)((mag * (int32_t)MOTOR_TIM_ARR) / MOTOR_SPEED_MAX);
}

static void motor_drive(TIM_HandleTypeDef *htim,
                        uint32_t in1_ch, uint32_t in2_ch,
                        int16_t speed)
{
    uint32_t ccr = speed_to_ccr(speed);

    if (speed > 0)
    {
        __HAL_TIM_SET_COMPARE(htim, in1_ch, ccr);
        __HAL_TIM_SET_COMPARE(htim, in2_ch, 0);
    }
    else if (speed < 0)
    {
        __HAL_TIM_SET_COMPARE(htim, in1_ch, 0);
        __HAL_TIM_SET_COMPARE(htim, in2_ch, ccr);
    }
    else
    {
        __HAL_TIM_SET_COMPARE(htim, in1_ch, 0);
        __HAL_TIM_SET_COMPARE(htim, in2_ch, 0);
    }
}

/* ------------------------------------------------------------------ */
/* Motors                                                              */
/* ------------------------------------------------------------------ */

void Motors_Init(void)
{
    /* Zero the compare registers before enabling outputs so nothing lurches
     * the instant the pins go live. */
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_3, 0);
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_4, 0);
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_1, 0);
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_2, 0);

    HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);   /* PB8 */
    HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_4);   /* PB9 */
    HAL_TIM_PWM_Start(&htim9, TIM_CHANNEL_1);   /* PE5 */
    HAL_TIM_PWM_Start(&htim9, TIM_CHANNEL_2);   /* PE6 */
}

void Motor_A_Set(int16_t speed)
{
#if MOTOR_A_INVERT
    speed = (int16_t)(-speed);
#endif
    motor_drive(&htim4, TIM_CHANNEL_3, TIM_CHANNEL_4, speed);
}

void Motor_B_Set(int16_t speed)
{
#if MOTOR_B_INVERT
    speed = (int16_t)(-speed);
#endif
    motor_drive(&htim9, TIM_CHANNEL_1, TIM_CHANNEL_2, speed);
}

void Motor_A_Brake(void)
{
    /* ARR+1 gives a compare value the counter never reaches, i.e. 100% duty,
     * so both inputs sit high for the whole period. */
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_3, MOTOR_TIM_ARR + 1U);
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_4, MOTOR_TIM_ARR + 1U);
}

void Motor_B_Brake(void)
{
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_1, MOTOR_TIM_ARR + 1U);
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_2, MOTOR_TIM_ARR + 1U);
}

void Motors_Brake(void)
{
    Motor_A_Brake();
    Motor_B_Brake();
}

void Motors_Coast(void)
{
    Motor_A_Set(0);
    Motor_B_Set(0);
}

/* ------------------------------------------------------------------ */
/* Servos                                                              */
/* ------------------------------------------------------------------ */

void Servos_Init(void)
{
    __HAL_TIM_SET_COMPARE(&htim12, TIM_CHANNEL_2, SERVO_CENTER_US);
    HAL_TIM_PWM_Start(&htim12, TIM_CHANNEL_2);
}

void Servo_SetMicroseconds(uint16_t us)
{
    if (us < SERVO_MIN_US)      us = SERVO_MIN_US;
    else if (us > SERVO_MAX_US) us = SERVO_MAX_US;

    __HAL_TIM_SET_COMPARE(&htim12, TIM_CHANNEL_2, us);
}

void Servo_SetRawUs(uint16_t us)
{
    if (us < SERVO_ABS_MIN_US)      us = SERVO_ABS_MIN_US;
    else if (us > SERVO_ABS_MAX_US) us = SERVO_ABS_MAX_US;

    __HAL_TIM_SET_COMPARE(&htim12, TIM_CHANNEL_2, us);
}

void Servo_SetAngle(uint8_t degrees)
{
    uint32_t us;
    if (degrees > 180U) degrees = 180U;
    us = SERVO_MIN_US + (((uint32_t)degrees * (SERVO_MAX_US - SERVO_MIN_US)) / 180U);
    Servo_SetMicroseconds((uint16_t)us);
}
/* ------------------------------------------------------------------ */
/* Bring-up test                                                       */
/* ------------------------------------------------------------------ */

void Motors_TestSequence(void)
{
    /* Steering sweep: centre, left, right, centre.
     * Microseconds, not angles - Phase 2 calibrates in these units. */
    Servo_SetMicroseconds(SERVO_CENTER_US);
    HAL_Delay(1000);
    Servo_SetMicroseconds(SERVO_MIN_US);
    HAL_Delay(1000);
    Servo_SetMicroseconds(SERVO_MAX_US);
    HAL_Delay(1000);
    Servo_SetMicroseconds(SERVO_CENTER_US);
    HAL_Delay(600);

    /* Motor A alone, ramp forward then reverse. */
    for (int16_t s = 0; s <= 600; s += 50)
    {
        Motor_A_Set(s);
        HAL_Delay(100);
    }
    Motor_A_Set(0);
    HAL_Delay(500);

    for (int16_t s = 0; s >= -600; s -= 50)
    {
        Motor_A_Set(s);
        HAL_Delay(100);
    }
    Motor_A_Set(0);
    HAL_Delay(500);

    /* Motor B alone, same pattern. */
    for (int16_t s = 0; s <= 600; s += 50)
    {
        Motor_B_Set(s);
        HAL_Delay(100);
    }
    Motor_B_Set(0);
    HAL_Delay(500);

    for (int16_t s = 0; s >= -600; s -= 50)
    {
        Motor_B_Set(s);
        HAL_Delay(100);
    }
    Motor_B_Set(0);
    HAL_Delay(500);

    /* Both together, then a hard brake. */
    Motor_A_Set(500);
    Motor_B_Set(500);
    HAL_Delay(1500);
    Motors_Brake();
    HAL_Delay(500);
    Motors_Coast();
}
